[project]
name = "phoneme-class-1d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.4",
    "torch>=2.7.0",
    "typer>=0.15.4",
]
